# Include Very Good Analysis als Basis
include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"

  errors:
    # Behandle diese als Fehler (nicht nur Warnungen)
    unused_import: error
    unused_local_variable: error
    dead_code: error
    invalid_annotation_target: ignore

  language:
    strict-casts: false
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Zusätzliche Rules die Very Good Analysis nicht hat
    - always_declare_return_types
    - avoid_print
    - avoid_unused_constructor_parameters
    - prefer_single_quotes
    - sort_constructors_first
    - unnecessary_overrides
    - avoid_empty_else
    - public_member_api_docs: false # Wenn du nicht überall Docs willst
    - lines_longer_than_80_chars: false # Wenn 80 chars zu kurz sind

# DCM Konfiguration
dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 5
    maximum-nesting-level: 5
    lines-of-code: 150

  metrics-exclude:
    - test/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  rules:
    # Code Quality Rules
    - no-empty-block
    - no-equal-then-else
    - avoid-unused-parameters
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - prefer-moving-to-variable

    # Flutter spezifisch
    - always-remove-listener
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-extracting-callbacks

  anti-patterns:
    - long-method
    - long-parameter-list
