name: auth_service
description: Flutter Package that provides complete code for email authentication using Firebase
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  firebase_auth: ^4.16.0
  flutter:
    sdk: flutter
  firebase_database: ^10.4.0
  firebase_storage: ^11.6.6
  firebase_core: ^2.25.4
  image_picker: ^1.0.7

dev_dependencies:
  flutter_lints: ^1.0.4
