// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBofOVOx9mNE2zXW7pNn5ETEQRXX4z-Vc8',
    appId: '1:1009825139558:web:9507af594d8131233c56a7',
    messagingSenderId: '1009825139558',
    projectId: 'gamegrove-e25ff',
    authDomain: 'gamegrove-e25ff.firebaseapp.com',
    databaseURL: 'https://gamegrove-e25ff-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gamegrove-e25ff.appspot.com',
    measurementId: 'G-FLJ3QW030M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApjnKSqi61et1qYndpAt4uEb1tP_c5R50',
    appId: '1:1009825139558:android:ccc42475142d0d933c56a7',
    messagingSenderId: '1009825139558',
    projectId: 'gamegrove-e25ff',
    databaseURL: 'https://gamegrove-e25ff-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gamegrove-e25ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8LU7zYRZz86rhwKG2Rsd7UNbJPk3JNEU',
    appId: '1:1009825139558:ios:1d25b1f9d26761113c56a7',
    messagingSenderId: '1009825139558',
    projectId: 'gamegrove-e25ff',
    databaseURL: 'https://gamegrove-e25ff-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gamegrove-e25ff.appspot.com',
    iosBundleId: 'com.schweizerle.gamerGrove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8LU7zYRZz86rhwKG2Rsd7UNbJPk3JNEU',
    appId: '1:1009825139558:ios:18b1231d73dd12053c56a7',
    messagingSenderId: '1009825139558',
    projectId: 'gamegrove-e25ff',
    databaseURL: 'https://gamegrove-e25ff-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gamegrove-e25ff.appspot.com',
    iosBundleId: 'com.schweizerle.gamerGrove.RunnerTests',
  );
}
