import 'package:flex_color_scheme/flex_color_scheme.dart';

class FlexSchemeX {
  static FlexScheme schemeFromName(String name) {
    switch (name) {
      case 'FlexScheme.bigStone':
        return FlexScheme.bigStone;
      case 'FlexScheme.rosewood':
        return FlexScheme.rosewood;
      case 'FlexScheme.espresso':
        return FlexScheme.espresso;
      case 'FlexScheme.purpleM3':
        return FlexScheme.purpleM3;
      case 'FlexScheme.gold':
        return FlexScheme.gold;
      case 'FlexScheme.blueM3':
        return FlexScheme.blueM3;
      case 'FlexScheme.blue':
        return FlexScheme.blue;
      case 'FlexScheme.greenM3':
        return FlexScheme.greenM3;
      case 'FlexScheme.green':
        return FlexScheme.green;
      case 'FlexScheme.red':
        return FlexScheme.red;
      case 'FlexScheme.mallardGreen':
        return FlexScheme.mallardGreen;
      case 'FlexScheme.purpleBrown':
        return FlexScheme.purpleBrown;
      case 'FlexScheme.deepPurple':
        return FlexScheme.deepPurple;
      case 'FlexScheme.redWine':
        return FlexScheme.redWine;
      case 'FlexScheme.amber':
        return FlexScheme.amber;
      case 'FlexScheme.aquaBlue':
        return FlexScheme.aquaBlue;
      case 'FlexScheme.bahamaBlue':
        return FlexScheme.bahamaBlue;
      case 'FlexScheme.barossa':
        return FlexScheme.barossa;
      case 'FlexScheme.blueWhale':
        return FlexScheme.blueWhale;
      case 'FlexScheme.blumineBlue':
        return FlexScheme.blumineBlue;
      case 'FlexScheme.brandBlue':
        return FlexScheme.brandBlue;
      case 'FlexScheme.cyanM3':
        return FlexScheme.cyanM3;
      case 'FlexScheme.damask':
        return FlexScheme.damask;
      case 'FlexScheme.deepBlue':
        return FlexScheme.deepBlue;
      case 'FlexScheme.deepOrangeM3':
        return FlexScheme.deepOrangeM3;
      case 'FlexScheme.dellGenoa':
        return FlexScheme.dellGenoa;
      case 'FlexScheme.ebonyClay':
        return FlexScheme.ebonyClay;
      case 'FlexScheme.flutterDash':
        return FlexScheme.flutterDash;
      case 'FlexScheme.greyLaw':
        return FlexScheme.greyLaw;
      case 'FlexScheme.hippieBlue':
        return FlexScheme.hippieBlue;
      case 'FlexScheme.indigo':
        return FlexScheme.indigo;
      case 'FlexScheme.indigoM3':
        return FlexScheme.indigoM3;
      case 'FlexScheme.jungle':
        return FlexScheme.jungle;
      case 'FlexScheme.limeM3':
        return FlexScheme.limeM3;
      case 'FlexScheme.mandyRed':
        return FlexScheme.mandyRed;
      case 'FlexScheme.mango':
        return FlexScheme.mango;
      case 'FlexScheme.material':
        return FlexScheme.material;
      case 'FlexScheme.materialBaseline':
        return FlexScheme.materialBaseline;
      case 'FlexScheme.materialHc':
        return FlexScheme.materialHc;
      case 'FlexScheme.money':
        return FlexScheme.money;
      case 'FlexScheme.orangeM3':
        return FlexScheme.orangeM3;
      case 'FlexScheme.outerSpace':
        return FlexScheme.outerSpace;
      case 'FlexScheme.pinkM3':
        return FlexScheme.pinkM3;
      case 'FlexScheme.redM3':
        return FlexScheme.redM3;
      case 'FlexScheme.sakura':
        return FlexScheme.sakura;
      case 'FlexScheme.sanJuanBlue':
        return FlexScheme.sanJuanBlue;
      case 'FlexScheme.shark':
        return FlexScheme.shark;
      case 'FlexScheme.tealM3':
        return FlexScheme.tealM3;
      case 'FlexScheme.verdunHemlock':
        return FlexScheme.verdunHemlock;
      case 'FlexScheme.vesuviusBurn':
        return FlexScheme.vesuviusBurn;
      case 'FlexScheme.wasabi':
        return FlexScheme.wasabi;
      case 'FlexScheme.yellowM3':
        return FlexScheme.yellowM3;
      default:
        return FlexScheme.redWine;
    }
  }
}
